name: Build Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Zip extension
        run: |
          cd dist
          zip -r ../qr-extension.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qr-extension
          path: qr-extension.zip
  release:
    needs: build
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: qr-extension

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: qr-extension.zip